export const runtimeText = {
  en: {
    network: "Network engine",
    desc: "Start proxy listeners, manage WireGuard peers, and inspect live traffic.",
    start: "Start TCP proxies",
    startVPN: "Start VPN + proxies",
    stop: "Stop all",
    running: "Running",
    stopped: "Stopped",
    builtIn: "Built-in TCP engine",
    vpnEngine: "WireGuard / UDP engine",
    preview: "Open the desktop app or run npm start to use the network engine.",
    secrets: "Credentials are encrypted by the operating system.",
    memory:
      "Browser service: secrets stay in memory and must be re-entered after restart.",
    listeners: "Proxy listeners",
    addListener: "Add listener",
    noListeners: "Add a proxy client, then create a listener for that client.",
    name: "Name",
    host: "Bind address",
    port: "Port",
    protocol: "Protocol",
    client: "Client",
    auth: "Require password",
    password: "Password",
    username: "Username",
    passwordHint:
      "Leave blank to keep the saved credential. Secrets are excluded from JSON exports.",
    create: "Create",
    save: "Save",
    cancel: "Cancel",
    remove: "Delete",
    edit: "Edit",
    copy: "Copy endpoint",
    copied: "Copied",
    servers: "WireGuard servers",
    addServer: "Create VPN server",
    endpoint: "Public endpoint host",
    address: "Tunnel address / CIDR",
    publicKey: "Public key",
    peers: "VPN peers",
    addPeer: "Add peer",
    peerAddress: "Peer tunnel IP",
    outbound: "Outbound",
    blocked: "Block",
    exportPeer: "Download .conf",
    vpnNote:
      "WireGuard runs in a userspace engine with per-peer routing. It does not replace the host default route. A reachable UDP endpoint is required for remote devices.",
    importVPN: "Import WireGuard client",
    profile: "Paste .conf profile",
    import: "Import",
    importHint:
      "One peer per outbound, an IP endpoint, and one tunnel address. Profile commands are rejected.",
    enginePath: "sing-box executable",
    browse: "Browse…",
    apply: "Validate engine",
    engineHelp:
      "Use an official sing-box 1.12+ build with WireGuard and gVisor support. This engine is required for VPN and UDP; TCP proxies run without it.",
    traffic: "Recent connections",
    target: "Destination",
    result: "Result",
    time: "Time",
    noTraffic: "No connections recorded yet.",
    active: "Active TCP connections",
    sent: "Uploaded",
    received: "Downloaded",
    runtimeRequired:
      "The desktop or local backend is required for this action.",
    stopBeforeEditing: "Stop the engine before editing configuration.",
    invalidListener: "Check the listener address, port, protocol and client.",
    authRequired:
      "Set a client password before enabling authentication. LAN listeners require authentication.",
    socks4Auth:
      "SOCKS4 has no password authentication; use a loopback listener or SOCKS5.",
    duplicateListener: "A listener already uses that address and port.",
    vpnEngineRequired:
      "Choose a sing-box executable in the engine settings first.",
    invalidWireGuard: "Check WireGuard keys, tunnel address and peer settings.",
    missingPrivateKey: "A required private key has not been saved.",
    vpnEndpointIP:
      "Use an IP address for the outbound VPN endpoint to avoid endpoint DNS ambiguity.",
    profileCommandsRejected:
      "Profiles with PreUp/PostUp/PreDown/PostDown commands are not accepted.",
    engineConfigRejected:
      "The VPN engine rejected this configuration. Check engine version/features and configuration fields.",
    engineVersionUnsupported:
      "Use sing-box version 1.12 or later with WireGuard/gVisor support.",
    engineUnavailable: "Could not launch the VPN engine.",
    engineExited: "The VPN engine exited. Traffic remains blocked.",
    operationFailed:
      "The operation failed. Check the configuration and try again.",
    EADDRINUSE: "A requested port is already in use.",
    EACCES: "The operating system denied access.",
    duplicateIdentity: "This client identity already exists.",
    invalidConfig: "Invalid configuration or missing reference.",
    invalidEndpoint: "Invalid hostname or port.",
    importConfig: "Import metadata JSON",
    importConfigHint:
      "Import replaces metadata after validation. Passwords and private keys are never included in a metadata backup.",
    confirmReplace:
      "Replace the current metadata configuration with this file?",
    confirmDelete: "Delete this item?",
    emptyPeers: "No peers. Create one and download its configuration.",
    engineSaved: "Engine validated.",
    saved: "Saved.",
    direct: "Direct (explicit)",
  },
  vi: {
    network: "Engine mạng",
    desc: "Chạy proxy listener, quản lý peer WireGuard và theo dõi lưu lượng thật.",
    start: "Chạy proxy TCP",
    startVPN: "Chạy VPN + proxy",
    stop: "Dừng tất cả",
    running: "Đang chạy",
    stopped: "Đã dừng",
    builtIn: "Engine TCP tích hợp",
    vpnEngine: "Engine WireGuard / UDP",
    preview: "Mở ứng dụng desktop hoặc chạy npm start để sử dụng engine mạng.",
    secrets: "Thông tin xác thực được mã hóa bằng hệ điều hành.",
    memory:
      "Bản server trình duyệt: bí mật chỉ ở RAM, cần nhập lại sau khi khởi động lại.",
    listeners: "Proxy listener",
    addListener: "Thêm listener",
    noListeners: "Thêm client proxy, sau đó tạo listener cho client đó.",
    name: "Tên",
    host: "Địa chỉ bind",
    port: "Cổng",
    protocol: "Giao thức",
    client: "Client",
    auth: "Yêu cầu mật khẩu",
    password: "Mật khẩu",
    username: "Tài khoản",
    passwordHint:
      "Để trống để giữ thông tin đã lưu. Bí mật không xuất ra bản sao lưu JSON.",
    create: "Tạo",
    save: "Lưu",
    cancel: "Hủy",
    remove: "Xóa",
    edit: "Sửa",
    copy: "Sao chép endpoint",
    copied: "Đã sao chép",
    servers: "WireGuard server",
    addServer: "Tạo VPN server",
    endpoint: "Host endpoint công khai",
    address: "Địa chỉ tunnel / CIDR",
    publicKey: "Public key",
    peers: "VPN peer",
    addPeer: "Thêm peer",
    peerAddress: "IP tunnel của peer",
    outbound: "Đầu ra",
    blocked: "Chặn",
    exportPeer: "Tải .conf",
    vpnNote:
      "WireGuard chạy qua engine userspace, định tuyến riêng từng peer và không thay default route của máy. Thiết bị từ xa cần truy cập được endpoint UDP.",
    importVPN: "Nhập WireGuard client",
    profile: "Dán profile .conf",
    import: "Nhập",
    importHint:
      "Mỗi đầu ra một peer, endpoint dạng IP và một địa chỉ tunnel. Từ chối profile chứa lệnh chạy hệ thống.",
    enginePath: "File thực thi sing-box",
    browse: "Chọn file…",
    apply: "Kiểm tra engine",
    engineHelp:
      "Dùng bản sing-box chính thức 1.12+ có WireGuard và gVisor. VPN và UDP cần engine này; proxy TCP chạy độc lập.",
    traffic: "Kết nối gần đây",
    target: "Đích đến",
    result: "Kết quả",
    time: "Thời gian",
    noTraffic: "Chưa ghi nhận kết nối.",
    active: "Kết nối TCP đang chạy",
    sent: "Đã gửi",
    received: "Đã nhận",
    runtimeRequired: "Thao tác này cần ứng dụng desktop hoặc backend local.",
    stopBeforeEditing: "Dừng engine trước khi sửa cấu hình.",
    invalidListener:
      "Kiểm tra địa chỉ, cổng, giao thức và client của listener.",
    authRequired:
      "Đặt mật khẩu client trước khi bật xác thực. Listener LAN phải có xác thực.",
    socks4Auth:
      "SOCKS4 không có xác thực mật khẩu; dùng listener loopback hoặc SOCKS5.",
    duplicateListener: "Địa chỉ và cổng này đã có listener.",
    vpnEngineRequired:
      "Chọn file thực thi sing-box trong phần cài đặt engine trước.",
    invalidWireGuard:
      "Kiểm tra khóa WireGuard, địa chỉ tunnel và thông tin peer.",
    missingPrivateKey: "Chưa lưu private key cần thiết.",
    vpnEndpointIP:
      "Endpoint VPN đầu ra phải dùng IP để tránh phân giải endpoint qua DNS không rõ đường đi.",
    profileCommandsRejected:
      "Không nhận profile có lệnh PreUp/PostUp/PreDown/PostDown.",
    engineConfigRejected:
      "Engine VPN từ chối cấu hình. Kiểm tra phiên bản/tính năng engine và các trường cấu hình.",
    engineVersionUnsupported: "Dùng sing-box từ 1.12 với WireGuard/gVisor.",
    engineUnavailable: "Không khởi chạy được engine VPN.",
    engineExited: "Engine VPN đã thoát. Lưu lượng vẫn bị chặn.",
    operationFailed:
      "Thao tác không thành công. Kiểm tra cấu hình rồi thử lại.",
    EADDRINUSE: "Một cổng được yêu cầu đang được sử dụng.",
    EACCES: "Hệ điều hành từ chối quyền truy cập.",
    duplicateIdentity: "Định danh client đã tồn tại.",
    invalidConfig: "Cấu hình không hợp lệ hoặc thiếu đối tượng tham chiếu.",
    invalidEndpoint: "Hostname hoặc cổng không hợp lệ.",
    importConfig: "Nhập metadata JSON",
    importConfigHint:
      "File nhập thay thế metadata sau khi kiểm tra. Bản sao lưu metadata không chứa mật khẩu hay private key.",
    confirmReplace: "Thay cấu hình metadata hiện tại bằng file này?",
    confirmDelete: "Xóa mục này?",
    emptyPeers: "Chưa có peer. Tạo peer và tải file cấu hình để sử dụng.",
    engineSaved: "Đã kiểm tra engine.",
    saved: "Đã lưu.",
    direct: "Trực tiếp (chỉ định rõ)",
  },
};
