import { createRequire } from 'node:module';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';
import net from 'node:net';
import { once } from 'node:events';
import { browserSession } from './browser-session.mjs';
const require = createRequire(import.meta.url);
const { serve } = require('../server/index.cjs');
const { dial } = require('../server/dial.cjs');
await mkdir('.tools/runtime-smoke', { recursive: true });
await mkdir('docs/assets', { recursive: true });
const data = await mkdtemp(resolve('.tools/runtime-smoke/data-'));
const app = await serve({ directory: data, port: 0 });
const browser = await browserSession();
const { send, evaluate, wait, click, fill } = browser;
const rpc = (method, args) => evaluate(`fetch('/api',{method:'POST',headers:{'Content-Type':'application/json','X-VPNtoProxy-Token':document.querySelector('meta[name="vpntoproxy-token"]').content},body:JSON.stringify(${JSON.stringify({ method, args })})}).then(r=>r.json()).then(r=>{if(r.error)throw new Error(r.error);return r.value})`);
const echo = net.createServer(s => { s.on('error', () => {}); s.on('data', b => s.write(b)); });
await new Promise(r => echo.listen(0, '127.0.0.1', r));
let connection;
try {
  await send('Page.navigate', { url: app.origin }); await wait(`document.querySelector('h1')?.textContent === 'Overview'`);
  await click('Add outbound'); await fill('[name="name"]', 'Local development'); await fill('[name="protocol"]', 'direct'); await click('Save configuration'); await wait(`!document.querySelector('dialog')`);
  const outbound = (await rpc('load')).outbounds[0];
  await click('Clients'); await click('Add client'); await fill('[name="name"]', 'Browser workspace'); await fill('[name="identity"]', 'browser-a'); await fill('[name="outboundId"]', outbound.id); await click('Save configuration'); await wait(`!document.querySelector('dialog')`);
  await click('Network engine'); await click('Add listener'); await fill('[name="name"]', 'Local mixed proxy');
  const temporary = net.createServer(); await new Promise(r => temporary.listen(0, '127.0.0.1', r)); const port = temporary.address().port; await new Promise(r => temporary.close(r));
  await fill('[name="port"]', String(port)); await evaluate(`document.querySelector('[name="auth"]').click()`); await fill('[name="password"]', 'smoke-only-password'); await click('Save'); await wait(`!document.querySelector('.runtime-overlay')`);
  await click('Start TCP proxies'); await wait(`document.querySelector('.runtime-panel .badge')?.textContent === 'Running'`);
  connection = await dial({ protocol: 'socks5', host: '127.0.0.1', port, username: 'browser-a' }, { host: '127.0.0.1', port: echo.address().port }, { password: 'smoke-only-password' });
  const reply = once(connection, 'data'); connection.resume(); connection.write('actual-proxy-traffic'); assert.equal((await reply)[0].toString(), 'actual-proxy-traffic');
  await click('Overview'); await wait(`document.querySelectorAll('.stat strong')[3]?.textContent === '1'`);
  await browser.screenshot('docs/assets/dashboard-en.png');
  connection.destroy(); connection = null;
  await click('Network engine'); await click('Stop all'); await wait(`document.querySelector('.runtime-panel .badge')?.textContent === 'Stopped'`);
  await click('Create VPN server'); await fill('[name="name"]', 'Home WireGuard'); await fill('[name="endpoint"]', 'vpn.example.com'); await click('Save'); await wait(`!document.querySelector('.runtime-overlay')`);
  await click('Add peer'); await fill('[name="name"]', 'Phone'); await fill('[name="identity"]', 'phone-a'); await fill('[name="address"]', '10.77.0.2'); await fill('[name="outboundId"]', outbound.id); await click('Save'); await wait(`!document.querySelector('.runtime-overlay')`);
  const config = await rpc('load'); const peer = config.clients.find(c => c.kind === 'vpn');
  assert.ok(peer.publicKey); assert.ok(!JSON.stringify(config).includes('smoke-only-password'));
  const conf = await rpc('exportPeer', { id: peer.id }); assert.match(conf, /PrivateKey =/); assert.match(conf, /Endpoint = vpn.example.com:51820/);
  await click('Start VPN + proxies'); await wait(`document.querySelector('[role="alert"]')?.textContent.includes('sing-box')`);
  assert.equal((await rpc('status')).vpn.state, 'stopped');
  await click('Add listener'); await click('Cancel');
  await browser.screenshot('docs/assets/network-en.png');
  await fill('select[aria-label="Interface language"]', 'vi'); await wait(`document.querySelector('h1')?.textContent === 'Engine mạng'`);
  await browser.screenshot('docs/assets/network-vi.png');
  await browser.reload(); await wait(`document.documentElement.lang === 'vi' && document.querySelector('h1')`);
  assert.equal((await rpc('load')).servers.length, 1);
  const denied = await fetch(app.origin + '/api', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ method: 'status' }) }); assert.equal(denied.status, 403);
  assert.deepEqual(browser.errors, []);
  console.log('Runtime browser smoke passed: UI → backend → real authenticated proxy traffic; secret redaction; VPN provisioning/export; missing-engine failure; localization; persistence; API authorization.');
} finally { connection?.destroy(); await app.close(); await new Promise(r => echo.close(r)); await browser.close(); }
